### ISSUE TITLE
[enhancement] Add URL links for each recipe

### ISSUE THREAD

**Issue by error0x01** [mattnotmax/cyberchef-recipes#15]
Hi,

the resource is really interesting, thanks for sharing!

Why not add to each recipe the specific link so the people can have direct access to them? For instance, the "Recipe 1 - Extract base64, raw inflate and code beautify" would have:
[https://gchq.github.io/CyberChef/#recipe=Regular_expression('User%20defined','%5Ba-zA-Z0-9%2B/%3D%5D%7B30,%7D',true,true,false,false,false,false,'List%20matches')From_Base64('A-Za-z0-9%2B/%3D',true,false)Raw_Inflate(0,0,'Adaptive',false,false)Generic_Code_Beautify()](
https://gchq.github.io/CyberChef/#recipe=Regular_expression('User%20defined','%5Ba-zA-Z0-9%2B/%3D%5D%7B30,%7D',true,true,false,false,false,false,'List%20matches')From_Base64('A-Za-z0-9%2B/%3D',true,false)Raw_Inflate(0,0,'Adaptive',false,false)Generic_Code_Beautify())

Thanks!

**Comment by mattnotmax** [comment]
Hi @error0x01 thanks for the idea. While it might help I also am wary about linking directly to the gchq.github.io site. Ideally people should run this offline or via a centralised corporate webserver. Some people may be blocked from the GCHQ version or may erroneously post sensitive data and inadvertently run afoul of their corporate IT policies. Thanks again!
