### ISSUE TITLE
Scenario 2 and Scenario 3 don't import

### ISSUE THREAD

**Issue by ticarpi** [mattnotmax/cyberchef-recipes#2]
Thanks for these great recipes.
Just FYI Scenarios 2 and 3 won't import currently due to escaping issues in the RegEx portions of the recipe.
Couple of extra slashes needed. Cheers.

**Comment by StefanKelm** [comment]
Hi @ticarpi 
If you copy the scenarios from the raw README file everything's fine.

**Comment by ticarpi** [comment]
Ah, fair enough.
I suspect most ppl would be using the github markdown-formatted page as I was, so they may also have the same issues.
Putting the compact JSON in a codeblock may be a good idea?

**Comment by mattnotmax** [comment]
Codeblocks it is! Thanks for testing and for letting me know.
